sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  on_failure: change
node_js:
  - "latest"
before_script:
  - npm prune
script:
  - PUBLIC_PATH=/trendingjs/ npm run build
after_success:
  - npm run semantic-release
  - bash ./deploy-gh-pages.sh
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"